### PR TITLE
Update to latest rustc & glfw

### PR DESCRIPTION
**Pull request by csherratt**

### CODE REVIEW

**Comment by indiv0** [comment]
@cmr any interest in merging this?

**Comment by cmr** [comment]
Woops, sorry, didn't notice this PR!

**Comment by cmr** [comment]
I'm happy to merge this :)

**Comment by cmr** [comment]
(Needs a rebase)

**Comment by csherratt** [comment]
@cmr rebased

**Comment by cmr** [comment]
Thanks :heart:

**Pull request merged**
